.TH DMWACOM 1 dmenuWacom\-VERSION
.SH NAME
dmenuWacom \- dmenu xsetwacom
.SH SYNOPSIS
.B dmenuWacom
.RB [ \-v ]
.SH DESCRIPTION
dmenuWacom is a script that allows you to configure the wacom pad on X.org.
DMWacom inside there are profiles for applications that I usually use, including
Krita, Gimp, Inkscape. This script is designed for a correct integration with 
DWM \- dynamic window manager suckless.org desktop, for further information
write me on my youtube channel.
.P
.B Warning \-
This script doesn't work with Wayland.
.SH OPTIONS
.TP
.B \-v
prints version information to stderr, then exits.
.SH USAGE
.B Button setting \-
allows you to set the keys of the pad.
.P
.B Application profiles \-
allow you to make use of ready-made profiles for
supported applications.
.P
