#!/bin/env zsh
PAD=$1
button1="+ctrl n -ctrl"
button2="f"
button3="+ctrl t -ctrl"
button4="+ctrl z -ctrl"

xsetwacom set "$PAD" Button 1 key $button1 &&
xsetwacom set "$PAD" Button 2 key $button2 &&
xsetwacom set "$PAD" Button 3 key $button3 &&
xsetwacom set "$PAD" Button 8 key $button4
